[[members]]
name = "五十嵐　雄人"
picture = ""
description = "ボールを投げてはディアを回し、気がつけばデビルですごい技を決めているシガラー。"
team = ""

[[members]]
name = "石川　開"
picture = "ishikawa.JPG"
description = "昨年・一昨年に続く、沖縄出身ボーラー。きれいなボールの軌道に注目！"
team = ""

[[members]]
name = "清水　夕歌"
picture = "shimizu.jpg"
description = "一緒にいると元気になれる、癒し系ジャグラー。ボールを投げたり、ディアボロを回したりする。"
team = ""

[[members]]
name = "田熊　大輝"
picture = ""
description = "コツコツジャグリングを続ける、琵琶湖大好きボーラー。ドーナツトップレベルのユーモアセンスを持つ。"
team = ""

[[members]]
name = "中村　伊吹"
picture = "nakamura.jpg"
description = "インテリアにもなるからボールは何個あっても困らない！ボールをこよなく愛するボーラー。"
team = ""

[[members]]
name = "山崎　創史"
picture = "yamazaki.jpg"
description = "オオサンショウウオとミスドが元気の源！縦横何でも上手なディアボラー。"
team = ""

[[members]]
name = "山田　覚巳"
picture = "yamada.jpg"
description = "ダイナミックな技をばんばんバンバン決めてくれるシガラー。某先輩へのいじりもばんばん決まってます！"
team = ""

