[[members]]
name = "石田"
picture = "ishida.jpg"
description = "28期のしっかり枠。華麗にシガーボックスを操る姿はさながら魔女。かなりの辛党だが、たまに出る毒舌も So spicy"

[[members]]
name = "岩田"
picture = "yuto-iwata.jpg"
description = "見るからに優しそうな彼。話してみるとその人の良さが分かる。高校時代はサッカー部だったこともあり、フットストールがとても上手い。また、人一倍熱心に練習をするため確実に上達している。その成長の可能性は計り知れない。"

[[members]]
name = "江川"
picture = "egawa.jpg"
description = "とってもフレンドリーなポイスピナー。すっごく視力が良いらしい。"

[[members]]
name = "岡"
picture = "oka.jpg"
description = "正統派ディアボラー。ディアボロだけでなく、口もよく回る。将棋も指せる。"

[[members]]
name = "川井"
picture = "kawai.jpg"
description = "三半規管強めディアボラー。座右の銘は急がばナナメ！オレンジ髪とチャイナドレスが元identity（？）"

[[members]]
name = "後藤"
picture = "gotou.jpg"
description = "福井から来たいつもにこにこ系リンガー。 驚異のコミュ力で誰とでもすぐに仲良くなれてしまう。 ドーナツ入りたての君はとりあえず彼女に話しかけてみるといいぞ！"

[[members]]
name = "谷崎"
picture = "tanizaki.jpg"
description = "3代目皿のお兄さん！明るい笑顔が魅力的。28期の、いやDonutsの光です。"

[[members]]
name = "辻󠄀(真)"
picture = "masaki-tsuji.jpg"
description = "5ボールを自在に扱うお手玉経験者。玉の数が増えると自慢してくる。"

[[members]]
name = "都留"
picture = "tsuru.jpg"
description = "たくさん走り、たくさん投げる。体操部にも所属するバイタリティに満ちたトスジャグラー。けん玉も嗜む。"

[[members]]
name = "長島"
picture = "nagashima.jpg"
description = "ボールもできるシガラー。夏からシガーを始めてぐんぐん上達している。授業よりサークルの方がよく見かける、、、"

[[members]]
name = "三浦"
picture = "miura.jpg"
description = "勉強もサークルも頑張るマジメなボーラー。 理科教員を目指しており、講義漬けの毎日を送る。 そんな彼には意外な一面もある。お酒が入ると…"

[[members]]
name = "宮原"
picture = "miyahara.jpg"
description = "学業、バイト、ジャグリングをそつなくこなす元・野良ディアボラー。キレキレの技と発言の裏には繊細な一面も。"

[[members]]
name = "牧野"
picture = "makino.jpg"
description = "高校始めのディアボラー。縦のうまさはピカイチ。28期のメロ担当は君に任せました。"