year = 2019
month = 5
day1 = 4
dow1 = "土"
day2 = 5
dow2 = "日"
firstStart = "13:00" # 1日目昼の部の開演時間
firstOpen = "12:30" # 1日目昼の部の開場時間
secondStart = "16:00" # 1日目夜の部の開演時間
secondOpen = "15:30" # 1日目夜の部の開場時間
thirdStart = "13:00" # 2日目昼の部の開演時間
thirdOpen = "12:30" # 2日目昼の部の開場時間

showtime = 40
place = "京都市東山青少年活動センター"
registerDeadline = "5月3日 (金) 21時" # 前日の夜でいい？ 
registerForm = "https://ticket.corich.jp/apply/97372" # 何も考えず載せてみる

[[casts]]
name = "白井　夢月"
tool = "ディアボロ"

[[casts]]
name = "戸板　治紀"
tool = "ポイ"

[[casts]]
name = "松巾　拓未"
tool = "ヨーヨー"

[[casts]]
name = "山下　巧"
tool = "クリスタル"

[[casts]]
name = "山下　湧志朗"
tool = "クラブ"

[[staffs]]
name = "小松原　裕"
position = "舞台監督"

[[staffs]]
name = "渡邉　優大"
position = "音響"

[[staffs]]
name = "吉村　比呂"
position = "照明"

[[staffs]]
name = "糟谷？" # 決まってたっけ？
position = "撮影"

[[staffs]]
name = "原田　優真"
position = "広報"

[[staffs]]
name = "富川　幹也"
position = "ウェブ"

[[staffs]]
name = "富川　幹也"
position = "チケット"

[[prices]]
target = "一般・大学生"
price = "500円"

[[prices]]
target = "大学新入生・高校生以下"
price = "300円"

